### PR TITLE
Overflow and spelling

### PR DESCRIPTION
**Pull request by Beedhan**
-changed overflow x
-changed spelling mistake in readme

### CODE REVIEW

**Comment by softmarshmallow** [comment]
@Beedhan  Could you submit the png of diff of the website? current master and your version.

Thanks for the PR

**Comment by Beedhan** [comment]
image
(current master)
image
my version (https://bridged-xyz-507mj88a1.vercel.app/)

It is showing x-scrollbar on current master
And about nav link I thought it might be little harder for someone to read

**Comment by softmarshmallow** [comment]
@Beedhan The overflow solutions seems ok. but we definitely need to talk to our designer about changing the color. Perhaps you can join our community and talk to our designer about the color visibility issue?

p.s. I can merge this right away if only color reverts back to original.

(And i also agree that it is hard to read.)

Join us on [slack](https://www.notion.so/bridgedxyz/Bridged-OSS-Community-c6983f668e3e4204aed8856da0e73483)

**Comment by softmarshmallow** [comment]
LGTM, fixes overflow issue

**Pull request merged**
